name: Test Docker Hub Authentication

on:
  workflow_dispatch:  # Manual trigger only

env:
  REGISTRY: docker.io
  IMAGE_NAME: oauth-oidc-mock-service

jobs:
  test-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug credentials
        run: |
          echo "Testing Docker Hub authentication..."
          echo "Username: ${{ secrets.DOCKERHUB_USERNAME }}"
          echo "Username length: ${#USERNAME}"
          echo "Token length: ${#TOKEN}"
          if [ -z "$USERNAME" ]; then
            echo "❌ DOCKERHUB_USERNAME secret is empty or not set"
          else
            echo "✅ DOCKERHUB_USERNAME secret exists"
          fi
          if [ -z "$TOKEN" ]; then
            echo "❌ DOCKERHUB_TOKEN secret is empty or not set"
          else
            echo "✅ DOCKERHUB_TOKEN secret exists"
          fi
        env:
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test Docker Hub login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Test image build (no push)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:test

      - name: Success message
        run: |
          echo "🎉 Docker Hub authentication and build test successful!"
          echo "You can now use the main CI/CD workflows."
